- name: play-level variables
  hosts:  local
  connection: local
  vars:
    COURSE: DevOps  #this is equal to COURSE=DevOps in shell
    TRAINER:  Siva
  tasks:
  - name: printing information using variables
    ansible.builtin.debug:
      msg:  "Hello this {{ COURSE }} course is trained by {{ TRAINER }}"  #in shell we use $var_name to get it's value here we use {{}}
      #variables should be mentioned within double quotes , only then ansible considers it as variable
  
  - name: printing information using variables again
    ansible.builtin.debug:
      msg:  "{{ TRAINER }} will train us {{ COURSE }} course"


#play level variables have global access across play. They can be called in any no.of tasks within the play

