- name: task level variables
  hosts:  local
  connection: local
  vars:
    COURSE: DevOps
    TRAINER:  Siva
  tasks:
  - name: varibles from taks1
    vars:
      COURSE: Ansible
      TRAINER:  Kumar
    ansible.builtin.debug:
      msg:  "Hello this {{ COURSE }} course is trained by {{ TRAINER }}"

  - name: varibles from taks2
    ansible.builtin.debug:
      msg:  "Hello this {{ COURSE }} course is trained by {{ TRAINER }}"

