# instead of self declaring variables we can also prompt them from user
# using vars_promt

- name: variables from prompt
  hosts:  local
  connection: local
  vars_promt:
  - name: username  #holds value entered by user
    prompt: Please enter your name?
    private:  false       #if we enter private as true then it wont be visbile on terminal. similar to 'read -s' in shell

  - name: password
    prompt: please enter your password
    private:  true        # as pass is private and we need to ensure protection i/m keeping private as true

  tasks:
  - name: this is to print vars from prompt
    ansible.builtin.debug:
      msg:  " Hi {{ username }}, your password is {{ password }}"