- name: data types in ansible
  hosts:  local
  connection: local
  vars:
    DURATION: 120  #this is number
    COURSE: DevOps  # this is string
    IS_LIVE: true # boolean
    TOOLS:   # this is list -> usaually list is defined with - in ansible -> in programmin glang they re defined as [ ]
      - linux
      - shell
      - ansible
    CONCEPTS: #map or dictionary or object -> in programming languages they are defined as {}
      CI: jenkins
      SCRIPTING:  "Shell,ansible,terraform,python"
  tasks:
    - name: ansible data types
      ansible.builtin.debug:
        msg:  " course is {{ COURSE }}, duration is {{ DURATION }}, is_live {{ IS_LIVE }}, Tools are {{ TOOLS }},
                Concepts are {{ CONCEPTS }}"