- name: conditions in ansible
  hosts:  local
  connection: local
  vars:
    NUMBER: 50
  tasks:
    - name: execute if number is less than or equal to 100
      when: NUMBER < 100
      ansible.builtin.debug:
        msg:  " {{ NUMBER }} is less than or equal to 100"