- name: control the flow with ansible facts
  hosts:  local
  become: yes
  connection: local
  tasks:
    - name: install nginx if os_family is redhat
      when: ansible_os_family == "RedHat"   #in ansible_facts list u can see os_family var holds info of os type. so here ansbile_os_family refers to os_family in ansible_Facts
      ansible.builtin.dnf:
        name: nginx
        state:  present

    - name: nginx service start
      ansible.builtin.service:
        name: nginx
        state:  started



    - name: install nginx if os_family is debian
      when: ansible_os_family == "Debian"
      ansible.builtin.apt:
        name: nginx
        state:  present
        state:  started

    - name: starting nginx service
      ansible.builtin.service:
        name: nginx
        state:  started