- name: intalling and uninstalling packages
  hosts:  local
  connection: local
  tasks:
    - name: installing and uninstalling
      loop:
        - { name: nginx, state: present }
        - { name: httpd, state: absent }
        - { name: zip, state: absent }
      ansible.builtin.package:
        name: "{{ item.name }}"
        state:  "{{ item.state }}"