- name: function usecase
  hosts:  local
  connection: local
  tasks:
    - name: default function # it is used when a variable declaration is not necessary and we wanted to skip var declaration
      ansible.builtin.debug:
        msg:  " Hi..{{ person | default('ramesh')}} "

    - name: split function  #used to split string based on specific parameters
      vars:
        names:  "ramesh,rakesh,rajesh"
      ansible.builtin.debug:
        msg:  "{{ names | split(',')}}"

    - name: dict2items usecase
      vars:
        COURSE:
          name: "DevOps"
          DURATION: 50hrs
      ansible.builtin.debug:
        msg:  "{{ COURSE | dict2items }}"

    - name: items2dict usecase
      vars:
        COURSE:
          - { "key": "name", "value": "DevOps"}
          - { "key": "duration", "value": "50hrs"}
      ansible.builtin.debug:
        msg:  "{{ COURSE | items2dict  }}"