- name: ansible error handling
  hosts:  local
  connectin:  local
  tasks:
    - name: check user existing or not
      ansible.builtin.command:  id roboshop  
      register: result
      ignore_errors:  true
#if user not existing command module will throw error so to handle that we need error handler
#we want ansible not to stop execution even if error triggered. we are just capturing output of command in var 

#now based on result code in output we need to perform next action

- name: creating user if not existing
  ansible.builtin.debug:
    msg:  "user not there hence creating user roboshop"
  when: result.rc != 0
  ansible.builtin.command:  useradd roboshop

- name: if user existing
  ansible.builtin.debug:
    msg:  "user already existing"